version: '3.9'
services:
  postgres:
    image: postgres:alpine
    container_name: libshary_db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bookshary_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - libshary_network

  api:
    restart: on-failure:5
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      args:
        - NODE_ENV=production
    container_name: libshary_api
    hostname: libshary_api
    ports:
      - '3000:3000'
    environment:
      - GOOGLE_CLIENT_SECRET=YOUR_GOOGLE_BOOKS_CLIENT_SECRET
      - GOOGLE_CLIENT_ID=YOUR_GOOGLE_BOOKS_CLIENT_ID
      - DATABASE_URL=postgresql://admin:password@libshary_db:5432/bookshary_db?schema=public
      - BOOKSEARCH_GRPC=libshary_booksearch:50051
      - WEB_URL=http://libshary_web:4200
    networks:
      - libshary_network
    depends_on:
      - postgres
      - rabbitmq

  web:
    restart: on-failure:5
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        - NODE_ENV=production
    container_name: libshary_web
    hostname: libshary_web
    ports:
      - '4200:4200'
    environment:
      - API_URL=http://libshary_api:3000
      - NEXTAUTH_URL=http://libshary_web:4200
      - NEXTAUTH_SECRET=secret

    networks:
      - libshary_network

  booksearch:
    restart: on-failure:5
    build:
      context: .
      dockerfile: apps/booksearch/Dockerfile
      args:
        - NODE_ENV=production
    container_name: libshary_booksearch
    hostname: libshary_booksearch
    ports:
      - '3001:3001'
    environment:
      - GOOGLE_BOOKS_API_KEY=YOUR_GOOGLE_BOOKS_API_KEY
      - HOST=libshary_booksearch
      - REDIS_URL=redis://libshary_redis:6379
    depends_on:
      - rabbitmq
      - redis
    networks:
      - libshary_network
  redis:
    image: redis:latest
    container_name: libshary_redis
    hostname: lishary_redis
    ports:
      - '6379:6379'
    networks:
      - libshary_network
volumes:
  postgres:

networks:
  libshary_network:
    name: libshary_network
    driver: bridge
