apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  NODE_ENV: 'development'
  DATABASE_NAME: 'libshary_dev'
  API_URL: 'http://dev-api.libshary.com'
  WEB_URL: 'http://dev.libshary.com'
  DATABASE_HOST: 'dev-postgres.database.svc'
