apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ingress.yaml
patches:
  - path: configmap.yaml
    target:
      kind: ConfigMap
      name: app-config
      namespace: libshary
  - target:
      kind: Service
      name: web
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
  - target:
      kind: Service
      name: grafana
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
