type ShelfModel {
  id: ID!
  name: String!
  description: String
  private: Boolean!
  ownerId: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  sections: [SectionModel!]!
}

"""
A date-time string at UTC, such as 2019-12-03T09:54:33Z, compliant with the date-time format.
"""
scalar DateTime

type BookModel {
  id: ID!
  title: String!
  authors: [String!]!
  description: String
  publishedAt: DateTime
  publisher: String
  pageCount: Float
  imageLinks: String
  isbn10: String
  isbn13: String
  googleBookId: String
  categories: [String!]
}

type SectionBookModel {
  id: ID!
  sectionId: ID!
  bookId: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  book: BookModel!
  section: SectionModel!
}

type SectionModel {
  id: ID!
  name: String!
  shelfId: ID!
  shelf: ShelfModel!
  createdAt: DateTime!
  updatedAt: DateTime!
  books: [SectionBookModel!]!
}

type SearchResponseDto {
  apiProvider: String!
  totalNumber: Float!
  limit: Float!
  offset: Float!
  books: [BookModel!]!
}

type Query {
  findSection(id: String!): SectionModel
  findAllSections: [SectionModel!]
  findSectionBooks(sectionId: String!): [SectionBookModel!]
  findAllSectionBooks: [SectionBookModel!]
  findShelf(id: String!): ShelfModel
  findAllShelves: [ShelfModel!]
  findBook(id: ID, googleBookId: ID): BookModel
  searchBooks(q: String, limit: Int, offset: Int, tags: [String!]): SearchResponseDto
}

type Mutation {
  createSection(createSectionInput: CreateSectionInput!): SectionModel!
  updateSection(id: String!, updateSectionInput: UpdateSectionInput!): SectionModel!
  removeSection(id: String!): SectionModel!
  createSectionBook(createSectionBookInput: CreateSectionBookInput!): SectionBookModel!
  updateSectionBook(updateSectionBookInput: UpdateSectionBookInput!, id: String!): SectionBookModel!
  removeSectionBook(sectionId: String!, bookId: String!): SectionBookModel!
  createShelf(createShelfInput: CreateShelfInput!): ShelfModel!
  updateShelf(id: String!, updateShelfInput: UpdateShelfInput!): ShelfModel!
  removeShelf(id: String!): ShelfModel!
}

input CreateSectionInput {
  name: String!
  shelfId: ID!
}

input UpdateSectionInput {
  name: String
}

input CreateSectionBookInput {
  googleBookId: ID!
  sectionId: ID!
}

input UpdateSectionBookInput {
  sectionId: String!
}

input CreateShelfInput {
  name: String!
  description: String
  private: Boolean!
  color: String
  defaultSections: Boolean!
}

input UpdateShelfInput {
  name: String
  description: String
  private: Boolean
  color: String
}