apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DATABASE_NAME: 'libshary_prod'
  API_URL: 'https://api.libshary.com'
  WEB_URL: 'https://libshary.com'
  DATABASE_HOST: 'prod-postgres.database.svc'
