apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: libshary
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector:
        node-role.kubernetes.io/application: 'true'
      containers:
        - name: api
          imagePullPolicy: IfNotPresent
          image: ghcr.io/vvcodeweb/libshary/libshary-api
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '200m'
          ports:
            - containerPort: 3000
          env:
            - name: DOCKER_DEFAULT_PLATFORM
              value: linux/amd64
            - name: WEB_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: WEB_URL
            - name: DATABASE_URL
              value: 'postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@postgres:5432/$(DATABASE_NAME)?schema=public'
            - name: BOOKSEARCH_GRPC
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BOOKSEARCH_GRPC

            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_CLIENT_ID
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AUTH_SECRET
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: libshary
spec:
  selector:
    app: api
  ports:
    - port: 3000
