apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: libshary
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: your-registry/libshary-api:latest # Update with your image
          ports:
            - containerPort: 3000
          env:
            - name: WEB_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: WEB_URL
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_URL
            - name: BOOKSEARCH_GRPC
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BOOKSEARCH_GRPC

            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_CLIENT_ID
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: libshary
spec:
  selector:
    app: api
  ports:
    - port: 3000
