apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksearch
  namespace: libshary
spec:
  selector:
    matchLabels:
      app: booksearch
  template:
    metadata:
      labels:
        app: booksearch
    spec:
      containers:
        - name: booksearch
          image: your-registry/libshary-booksearch:latest
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: 'production'
            - name: PORT
              value: '3001'
            - name: GOOGLE_BOOKS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_BOOKS_API_KEY
            - name: HOST
              value: 'booksearch'
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_URL
---
apiVersion: v1
kind: Service
metadata:
  name: booksearch
  namespace: libshary
spec:
  selector:
    app: booksearch
  ports:
    - port: 3001
