apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksearch
  namespace: libshary
spec:
  selector:
    matchLabels:
      app: booksearch
  template:
    metadata:
      labels:
        app: booksearch
    spec:
      nodeSelector:
        node-role.kubernetes.io/application: 'true'
      containers:
        - name: booksearch
          imagePullPolicy: IfNotPresent
          image: ghcr.io/vvcodeweb/libshary/libshary-booksearch
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10

          ports:
            - containerPort: 3001
            - containerPort: 50051
          env:
            - name: DOCKER_DEFAULT_PLATFORM
              value: linux/amd64
            - name: PORT
              value: '3001'
            - name: GOOGLE_BOOKS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_BOOKS_API_KEY
            - name: HOST
              value: '0.0.0.0'
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_URL
---
apiVersion: v1
kind: Service
metadata:
  name: booksearch
  namespace: libshary
spec:
  selector:
    app: booksearch
  ports:
    - port: 3001
      name: booksearch
    - port: 50051
      name: grpc
