apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - prometheus-config.yaml
  - monitoring.yaml
  - storage.yaml
  - postgres.yaml
  - redis.yaml
  - api.yaml
  - web.yaml
  - booksearch.yaml
