apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - prometheus-config.yaml
  - monitoring.yaml
  - postgres.yaml
  - redis.yaml
  - api.yaml
  - web.yaml
  - booksearch.yaml

images:
  - name: ghcr.io/vvcodeweb/libshary/libshary-api
    newTag: v0.0.0
  - name: ghcr.io/vvcodeweb/libshary/libshary-web
    newTag: v0.0.0
  - name: ghcr.io/vvcodeweb/libshary/libshary-booksearch
    newTag: v0.0.0
