apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: libshary
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: your-registry/libshary-web:latest # Update with your image
          ports:
            - containerPort: 4200
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: API_URL
            - name: NEXTAUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: WEB_URL
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: NEXTAUTH_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: libshary
spec:
  selector:
    app: web
  ports:
    - port: 4200
