apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: libshary
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      nodeSelector:
        node-role.kubernetes.io/application: 'true'
      containers:
        - name: web
          imagePullPolicy: IfNotPresent
          image: ghcr.io/vvcodeweb/libshary/libshary-web
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
          ports:
            - containerPort: 3000
          env:
            - name: DOCKER_DEFAULT_PLATFORM
              value: linux/amd64
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: API_URL
            - name: NEXTAUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: WEB_URL
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: NEXTAUTH_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: libshary
spec:
  selector:
    app: web
  ports:
    - port: 4200
      targetPort: 3000
