name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: |
            ## What's Changed

            <!-- Release notes will be added manually -->

            ## Images

            The following images are available:
            - `ghcr.io/${{ github.repository }}/libshary-api:${{ steps.get_version.outputs.VERSION }}`
            - `ghcr.io/${{ github.repository }}/libshary-web:${{ steps.get_version.outputs.VERSION }}`
            - `ghcr.io/${{ github.repository }}/libshary-booksearch:${{ steps.get_version.outputs.VERSION }}`
