name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --cache --prefer-offline
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected --target=lint

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --cache --prefer-offline
      - run: npx nx run prisma:generate
      - uses: nrwl/nx-set-shas@v4

      - run: npx nx affected --target=test

  e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --cache --prefer-offline
      - run: npx nx run prisma:generate

      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected --target=e2e --exclude=api-e2e
